### ISSUE TITLE
Nothing happens after using TwitterAuth.login() on iOS 11

### ISSUE THREAD

**Issue by arminsal1** [tipsi/tipsi-twitter#12]
After updating my device to iOS 11, updating this module to 2.0.0, installing the TwitterKit 3.1 pod, and reconfiguring my info.plist to current standards, twitter login is no longer working on my device.

What happens: It redirects to my installed Twitter app with a prompt to connect my account to my application's Twitter app. After pressing the "connect" button it redirects back to my application, but nothing happens. No errors were caught in debug mode and there's no related messages in my dev console. Am I missing something?

Twitter login worked flawlessly before updating so I'm not sure what's going on.

Here's my code:
```
_twitterAuth = async () => {
    this.setState({showScreen:false})
    try {
      const result = await TwitterAuth.login()
      console.log("result", result)
      console.log('User id:', result.userId)
    } catch (error) {
      console.log('Login error:', error)
    }
  }
```

**Comment by isnifer** [comment]
@arminsal1 we need to check it with twitter app. We didn't do that

**Comment by arminsal1** [comment]
@isnifer What do you think I should do?

**Comment by isnifer** [comment]
@arminsal1 not sure, just wait :)

**Comment by arminsal1** [comment]
I fixed the issue! Turns out it was my fault. I didn't add the new code for TwitterKit 3 to my App Delegate. Works perfectly now
