### ISSUE TITLE
No success response

### ISSUE THREAD

**Issue by ankitbisht143** [tipsi/tipsi-twitter#14]
I am using tipsi-twitter in my react native app. All working fine but after connecting my app with twitter account I am not receiving any response.

handleTwitterLoginFinished = async () => {
      try {
        const result = await TwitterAuth.login()
        console.log('User id:', result.userId)
      } catch (error) {
        console.log('Login error:', error)
      }
    }
In this method I am not getting result.

**Comment by isnifer** [comment]
Hi, @ankitbisht143! We return an object with [next fields](https://github.com/tipsi/tipsi-twitter/blob/master/ios/TPSTwitterModule/TPSTwitterModule.m#L13-L16) in the success response.
So, you should get `userId` from **`userID`** field, not `userId`

**Comment by ankitbisht143** [comment]
I am still not getting anything.

handleTwitterLoginFinished = async () => {
try {
const result = await TwitterAuth.login()
alert('checking');
console.log('User id:', result.userID)
} catch (error) {
console.log('Login error:', error)
}
}

I am not even getting alert of message 'checking'. How to receive response?

**Comment by isnifer** [comment]
So, @ankitbisht143 what `result` contains?

**Comment by kabhimanyu** [comment]
const result = await TwitterAuth.login()
console.log('User id:', result.userID)

For some reason the console.log after await is never executed. Any ideas

**Comment by isnifer** [comment]
@kabhimanyu did you catch `Login error`?

**Comment by ankitbisht143** [comment]
Problem solved after adding application:openURL:options(which returns a boolean value) method in appDelegate file.
