### ISSUE TITLE
cannot load such file -- xcodeproj (LoadError)

### ISSUE THREAD

**Issue by developersoul** [tipsi/tipsi-twitter#17]
When I try to link the libray I receive the follow error from the ruby script.

```bash
cannot load such file -- xcodeproj (LoadError)
from node_modules/tipsi-twitter/scripts/post-link-ios.rb:3:in `<main>'
```

**Comment by isnifer** [comment]
@developersoul please try:
```sh
$ [sudo] gem install xcodeproj
```

**Comment by developersoul** [comment]
Thanks @isnifer... a question, the script add this to AppDelegate.m 

```objectivec
 [[Twitter sharedInstance] startWithConsumerKey:@"" consumerSecret:@""];
```
And 
```objectivec
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options {
  return [[Twitter sharedInstance] application:app openURL:url options:options];
}

```

Because is necessary to make it works the library.

I make a PR with this steps, but I see then I can cause this is a organization.

**Comment by isnifer** [comment]
@developersoul we have already a migration guide which contains these steps, look here - https://github.com/tipsi/tipsi-twitter/pull/16/files

**Comment by isnifer** [comment]
This PR will be merged ASAP

**Comment by developersoul** [comment]
That it's, thanks again @isnifer.

**Comment by isnifer** [comment]
@developersoul You're welcome. I'm closing an issue.
