### ISSUE TITLE
Error: Can not Load Account on IOS

### ISSUE THREAD

**Issue by okcxl3** [tipsi/tipsi-twitter#28]
After I ran TwitterAuth.login(), the twitter authentication page did not open up. However, an error was thrown with the message "Error: Can not Load Account".  Was this error caused due to invalid consumer key and secret?
I had initiated TwitterAuth with my consumer key and secret with
TwitterAuth.init({
    twitter_key: 'LI8Dr0ysVMQNPGNqbL8DOXH4N',
    twitter_secret: 'lKZ3lidk7xguxnqaxu1xchZqQPTEkKJpJw898BcmBSYxlVumGK',
}).

**Comment by densa** [comment]
@okcxl3 please check twitter app settings https://developer.twitter.com/en/docs/basics/callback_url.html

**Comment by isnifer** [comment]
@okcxl3 you need to define `Callback URL` on twitter dev portal as:
```sh
twitterkit-%YOU_TWITTER_KEY%://
```
instead of `twitterkit://`. For example:
```sh
twitterkit-UogNcEsnW5g44bIaFEWIM0e4w://
```
