### ISSUE TITLE
Android install not working: Could not find com.twitter.sdk.android:twitter:2.3.0

### ISSUE THREAD

**Issue by BrendanBerkley** [tipsi/tipsi-twitter#8]
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.twitter.sdk.android:twitter:2.3.0.
     Required by:
         MyRedactedApp:app:unspecified > MyRedactedApp:tipsi-twitter:unspecified
```

That's the seemingly relevant error when I run `yarn run android`. 

I followed the readme (and iOS works fine), so everything should be where it's supposed to be, with the exception of the Fabric thing. I put the lines in the XML file, but I don't have an API key. Perhaps that's relevant? I'm not really sure what Fabric is, but you don't have an API key in your example folder so I'm guessing this isn't too important.

EDIT: Digging into this a bit more. Opened up SDK Manager in Studio, saw that I'm working with 25, so that's definitely above 16.

android/app/build.gradle,  
android/app/src/main/java/com/swoonmobile/MainApplication.java,  
android/settings.gradle, and  
android/app/src/main/AndroidManifest.xml 

are the only four files that get changes for Android, correct? Seems a bit simple compared to iOS, which required a few hundred new files, mostly from that TwitterKit pod. Is there some Android equivalent that I need to be including somewhere?

**Comment by isnifer** [comment]
Hi, @BrendanBerkley! Thank you for your issue. Let's check your installation and verify changes. I've installed a fresh RN application and add `tipsi-twitter` into it here https://github.com/isnifer/tipsi-twitter-issue-8/commit/9fc7986d1e84d67707d2d80798eaff1f54c57702.
Also, please tell me, do you have any extra symbols in `android/build.gradle`?

**Comment by bufke** [comment]
Hello - I work with Brendan and was able to reproduce it. I think it's due to a failure on the link step.

node_modules/tipsi-twitter/scripts/post-link.sh: 3: [: Linux: unexpected operator

```
#!/bin/sh

if [ "$(uname)" == "Darwin" ]; then
  ruby $(dirname "$0")/post-link-ios.rb
fi

$(dirname "$0")/post-link-android.sh
```

However removing the bad if statement didn't actually fix it. Next I checked every file edited on that link you sent and found that android/build.gradle didn't update properly with `maven { url "https://maven.fabric.io/public" }` . Manually editing that fixed the build error for me.

So I think there are two issues. The script doesn't correctly detect non-Darwin OS's to skip iOS and it doesn't add the maven url.

**Comment by isnifer** [comment]
@bufke ok, thank you for the explanation. I will check link script on Linux

**Comment by BrendanBerkley** [comment]
Can confirm what @bufke was saying. I ran `link` in a Mac terminal so I didn't get his first issue, but adding `maven { url "https://maven.fabric.io/public" }` to `android/build.gradle` made everything work for me.

Your fresh RN application did build for me on Ubuntu/Android emulator. Thanks for taking the time to set it up.

**Comment by isnifer** [comment]
@BrendanBerkley got it!

**Comment by isnifer** [comment]
@BrendanBerkley @bufke please update to 1.1.1

**Comment by BrendanBerkley** [comment]
Never followed up on this, but...thank you for resolving this!
